### PR TITLE
Auto-detect chan_id

### PR DESCRIPTION
**Pull request by m00ninite**
Automatically grabs the appropriate channel ID. One less thing for the user to type in :)

### CODE REVIEW

**Comment by RooSoft** [comment]
Great idea! Will try to modify it using `jq` instead of `grep`.

**Comment by m00ninite** [comment]
Oh yea, that's probably cleaner. I forgot jq was part of the requirements list. I'm not personally very familiar with it, so I'll leave that up to you. :)

**Comment by RooSoft** [comment]
Thing is, I am not really using igniter at the moment, so, would be nice if someone (@m00ninite) could test this so I don't merge it blindly

**Comment by m00ninite** [comment]
Sure thing, I can test

**Comment by vv01f** [comment]
had the same idea and was even a bit fast on opening an issue… then saw the pr;
I now select with jq with `jq -c '.channels[] | select(.remote_pubkey == "'${pubkey}'") | flatten | .[3]'` (not a pro on jq, so I don't claim it to be the best selector; possible that `chan_id` is not 3rd for all times)
though it has the advantage that a double/multiple entry for the same pubkey would result in all channel_points being listed, so this should also be tested for just in case even when rarely will happen.

**Comment by RooSoft** [comment]
That improvement would be much appreciated. It would need to be throughly tested prior to be merged as the script's stability is paramount, though.

I agree with @vv01f that the array index could potentially end up crashing in some circumstances.

Any contribution including a tested and embedded version of the `jq` command would most probably end up being merged.

**Comment by vv01f** [comment]
@RooSoft now saw that `grep` already is used to identify dockerized `lncli`
@m00ninite I went playing with `jq` a bit as I wanted to know better … just have no ring to test with at the moment

 ```
 # initial channel to transmit from
OUTGOING_CHAN_ID=$($LNCLI listchannels | jq -r '.channels[] | select( .remote_pubkey == "'${FIRST_PUBKEY}'" ) | { chan_id } | flatten | .[0]' )
CHAN_COUNT=$(echo "${OUTGOING_CHAN_ID}" | wc -l)
if test ${CHAN_COUNT} -ne 1 ; then
        >&2 printf "Error: more than one channel to first public key:\n\n${OUTGOING_CHAN_ID}\n"
        exit 1
fi
if test -z "${OUTGOING_CHAN_ID}"; then
        >&2 printf "route incomplete or no chan id found.\n"
        exit 2
fi
```

* declaration of `$LNCLI` needs to be above, `wc` added to dependencies
* step by step filtering and reducing the output by the field names only
* array index is used only to unwrap the single value from the array
* option `-r` removes the quotes from the value
* `CHAN_COUNT` can as well be inline without state or used in output

still missing: an option to override `OUTGOING_CHAN_ID` in case of more than a single channel for the first peer.

also thought of:
+ ring files with policy settings
+ automation for connection over opening and waiting for chan point (tx confirmed) … waiting for fee limit (e.g. 0), balance and set policy to (probably non-zero) "normal"

**Comment by RooSoft** [comment]
Thanks @m00ninite for the pull request.

Removing a parameter is a great idea.

Keeping the script stable is the most important thing, though.

This pull request makes assumptions about items in an array. Because of this, I am pretty sure it's not bulletproof.

You're welcome to send an improved version, but as this hasn't gotten any traction in three months, it will be closed.

**Pull request closed without merging**
