### PR TITLE
added command to connect to all peers of the ring of fire.

### PR DESCRIPTION
**Pull request by ramondevries**
As a ring leader you want to be able to connect to all peers of the ring of fire to test connection of all peers. 
The PR will add this command to the igniter script.

### CODE REVIEW

**Comment by RooSoft** [comment]
@dsbaars are you equiped to test this awesome PR?

**Comment by dsbaars** [comment]
I am on a long trip at least until Christmas so unfortunately not right now

**Comment by RooSoft** [comment]
> I am on a long trip at least until Christmas so unfortunately not right now

Do you know anybody who can?

**Comment by Tinus016** [comment]
> > I am on a long trip at least until Christmas so unfortunately not right now
> 
> Do you know anybody who can?

I'm not @dsbaars but I can and I've tested it, and it worked (Raspiblitz V1.8)

Tested with the participants of the  #SRROF_1Msats_53rdRING 

Note: i have shorted the address dude privacy reasons.

```
a****@192.***.*.*:~/igniter(main) ₿ ./igniter.sh connect
Already connected to: 02ec23c7c0c1adb58a46f6ca5...
Connecting to: 034f0854c5b3233af6f24dacc38bf01d...
{

}
Connecting to: 02e9aa24976253137610291c127517592...
{

}
Connecting to: 0322ffef979b5977f644967968e1a3673f...
{

}
Connecting to: 03d608e2311bf91fe415a407e226632906...
{

}
Connecting to: 0290fe12d15c563e26af79e6eac924c92c4...
{

}
Already connected to: 03f55b4f277b85df749ce23e4f5525.....
a****@192.***.*.*:~/igniter(main) ₿ 
```

**Comment by RooSoft** [comment]
Great, thanks guys for the contribution, will merge this right now.

**Review by RooSoft — APPROVED** [review]

**Comment by ramondevries** [comment]
Today I took part in a ring balance in SRROF_1Msats_54thRING, the ringleader had a debian installation with docker and got several errors:

./igniter.sh: line 41: docker exec -i lnd lncli: command not found

Will need to investigate this.

Config of ring leader:

Debian GNU/Linux 10 (buster)
Docker version 20.10.21, build baeda1f
Docker Compose version v2.12.2
Running on Raspberry Pi 4 and all with docker compose

**Comment by RooSoft** [comment]
Looks like the `docker` command is not available in the context of the current user.

From memory, default installations require sudo privileges to execute it.

**Comment by Tinus016** [comment]
Did he make the file executable? Like `chmod u+x igniter.sh`

**Comment by Tinus016** [comment]
> Did he make the file executable? Like `chmod u+x igniter.sh`

Never mind..He did, otherwise he has no permissions to execute the file anyway

**Comment by RooSoft** [comment]
> > Did he make the file executable? Like `chmod u+x igniter.sh`
> 
> Never mind..He did, otherwise he has no permissions to execute the file anyway

Yeah, it executes up until line 41, point at which it complains it doesn't know where the docker executable is.

**Pull request merged**
