### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ibz**

### CODE REVIEW

**Comment by RooSoft** [comment]
This is real good news!

I'd say it's much better than a potential improvement... Just upgrade your bullet point under a `##` header above `What can be improved`, such as `Use it straight from your umbrel` and maybe explain in more details how this works.

**Comment by RooSoft** [comment]
I may end up refactoring the whole README later, but I'll let you create that commit if you like.

**Review by RooSoft — CHANGES_REQUESTED** [review]
Create a new header explaining this

**Comment by ibz** [comment]
Sure, you can refactor as you wish. Just wanted to leave a note. I think it's quite an improvement, but it depends on everybody's case. For now, Lightning Shell is only on Umbrel and Citadel, so for those using other platforms, the "lncli must be in the path" would still apply.

BTW, under "Prerequisites", it seems that the points about editing the script are still there. When in fact it's about the config file now ...

**Comment by RooSoft** [comment]
Ok thanks @ibz, I will merge this tomorrow and then make the fixes on top of them.

**Pull request merged**
