### PR TITLE
Move configuration to a separate file.

### PR DESCRIPTION
**Pull request by ibz**
Hey! I moved the configuration to a separate file. I think the usability is better this way.

Planning to include `igniter` in [`lightning-shell`](https://github.com/ibz/lightning-shell/).

Cheers!

### CODE REVIEW

**Review by RooSoft — COMMENTED** [review]
That seems like a great idea!

Will try it soon and probably merge it.

Thanks for the great contribution, and for including igniter in lightning-shell!

**Comment by ibz** [comment]
Thank you!

Uh, I guess I should have edited the README as well.

**Comment by ibz** [comment]
> Thanks for the great contribution, and for including igniter in lightning-shell!

I want to include all useful LN TUI apps.

BTW, it would be useful if you push git tags from time to time, that can be used as "versions". It's not required, just nicer...

**Comment by RooSoft** [comment]
[There](https://github.com/RooSoft/igniter/releases/tag/1.0.0) you go

**Pull request merged**
